#!/usr/bin/env node
/**
 * Writes the build stamp used by the footer, the service-worker cache key and
 * the /__build endpoint. Run it before every dev session and deploy.
 *
 * Build number = number of commits on the current branch (monotonic, no state
 * to keep in the repo), falling back to 0 for a fresh clone with no history.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function git(command, fallback) {
  try {
    return execSync(command, { cwd: root, stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return fallback;
  }
}

const commitCount = Number.parseInt(git("git rev-list --count HEAD", "0"), 10) || 0;
const info = {
  buildNumber: commitCount + 1,
  buildDate: new Date().toISOString(),
  commit: git("git rev-parse --short HEAD", "uncommitted"),
  branch: git("git rev-parse --abbrev-ref HEAD", "unknown"),
};

writeFileSync(join(root, "public/build-info.json"), `${JSON.stringify(info, null, 2)}\n`);
writeFileSync(
  join(root, "public/build-info.js"),
  `/* Generated by scripts/build-info.mjs - do not edit. */\n/* self, not window: the service worker imports this file too. */\nself.BUILD_INFO = ${JSON.stringify(info, null, 2)};\n`,
);

console.log(`build ${info.buildNumber} (${info.commit}) ${info.buildDate}`);
